<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <RootNamespace>RIKA_IMBANIKA_LIFE_HELPER</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>LIFE HELPER PROGRAM FILES\Images\KOSHKA.ico</ApplicationIcon>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="LIFE HELPER PROGRAM FILES\Images\KOSHKA.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="RIKA IMBANIKA HELPER PROGRAM FILES\Images\" />
  </ItemGroup>

</Project>
